#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif
#include <wx/filefn.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>
#include <wx/filedlg.h>
#include <wx/filename.h>
#include <wx/image.h>
#include <wx/bitmap.h>
#include <wx/dcmemory.h>
#include <wx/dcscreen.h>
#include <wx/dcclient.h>
#include <wx/dcgraph.h>
#include <wx/graphics.h>
#include <wx/wfstream.h>

#ifdef _WIN32
#include <Windows.h>
#else
#include <unistd.h>
#endif

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{	
	protected:
		// Handlers for MyFrame1 events.
		void m_button_save_click( wxCommandEvent& event );
		void m_checkBox_banan_check( wxCommandEvent& event );
		void m_slider_position_onscroll( wxScrollEvent& event );
		void m_button_color_click( wxCommandEvent& event );
		void m_choice_star_onchoice( wxCommandEvent& event );
		virtual void MyFrame1_OnPaint( wxPaintEvent& event ) override{draw_things();}   
        virtual void MyFrame1_OnUpdateUI( wxUpdateUIEvent& event ) override
		{
			draw_things();
			if(m_checkBox_banan->IsChecked())
			{
				if(m_slider_position->GetValue() == 100)
				{
					m_slider_position->SetValue(m_slider_position->GetValue()-25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()-25);
					m_slider_position->SetValue(m_slider_position->GetValue()-25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()-25);
					m_slider_position->SetValue(m_slider_position->GetValue()-25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()-25);
					m_slider_position->SetValue(m_slider_position->GetValue()-25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()-25);
				}
				else if(m_slider_position->GetValue() == 0)
				{
					
					m_slider_position->SetValue(m_slider_position->GetValue()+25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()+25);
					m_slider_position->SetValue(m_slider_position->GetValue()+25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()+25);
					m_slider_position->SetValue(m_slider_position->GetValue()+25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()+25);
					m_slider_position->SetValue(m_slider_position->GetValue()+25);
					m_gauge_position->SetValue(m_gauge_position->GetValue()+25);
				}	
			}
		}
	public:
		wxColor kolor = wxColor(0,0,0);
    	wxBitmap bitmap;
    	wxBitmap bananbitmap;
		GUIMyFrame1( wxWindow* parent );
		void draw_things(); 

};

#endif // __GUIMyFrame1__
